"""Populate and set updated_at to NOT NULL

Revision ID: cbe9a2810e00
Revises: 238081fb30fb
Create Date: 2025-04-13 10:43:55.266334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cbe9a2810e00'
down_revision: Union[str, None] = '238081fb30fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- Manual Step: Populate NULL updated_at values ---
    op.execute("UPDATE pdfs SET updated_at = created_at WHERE updated_at IS NULL")
    op.execute("UPDATE users SET updated_at = created_at WHERE updated_at IS NULL")
    # --- End Manual Step ---
    
    op.alter_column('pdfs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('pdfs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
